create or replace TABLE TEST_DB.TEST_SCHEMA.OFFICEWORKFORCEMETRICS (
	MEASURENAME VARCHAR(30),
	OFFICENUMBER NUMBER(38,0),
	FISCALMONTHNBR NUMBER(38,0),
	COMPLETEDWEEKS NUMBER(38,0),
	DAYSINCALENDARMONTH NUMBER(38,0),
	MEASUREACTUAL NUMBER(12,2),
	MEASUREBUDGET NUMBER(12,2),
	LOADEDDATE DATE,
	constraint PK primary key (MEASURENAME, OFFICENUMBER, FISCALMONTHNBR)
);